#!/usr/bin/env bash

function startbeancount(){
    if ! grep -qs '/home/stephan/ledger ' /proc/mounts; then
        cryfs /home/stephan/Sync/ledger/ /home/stephan/ledger
    fi
    cd /home/stephan/ledger/beancount
    source .venv/bin/activate
}

function stopbeancount(){
    cd /home/stephan/ledger/beancount
    deactivate
    cd /home/stephan
}

startbeancount

