#!/usr/bin/env bash

function startbeancount(){
    cd /home/stephan/ledger/beancount
    source .venv/bin/activate
}

function stopbeancount(){
    cd /home/stephan/ledger/beancount
    deactivate
    cd /home/stephan
}

startbeancount

