#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  height=32
  blur_radius=0
  position=top
  sticky=off
  padding_left=10
  padding_right=10
  color=$BAR_COLOR
)
sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items
defaults=(
  updates=when_shown
  drawing=on
  icon.font="Symbols Nerd Font:1000-em:17.0"
  icon.color=$ICON_COLOR
  icon.y_offset=1
  label.font="Monaspace Neon Var:SemiBold:14.0"
  label.color=$FG_COLOR
  highlight.color=$HIGHLIGHT_COLOR
  background.color=$BAR_COLOR
  background.corner_radius=10
  background.height=24
  label.padding_left=4
  label.padding_right=10
  icon.padding_left=10
  icon.padding_right=4
)
sketchybar --default "${defaults[@]}"

##### Aerospace WM Space Indicators #####
sketchybar --add event aerospace_workspace_change

SPACE_ICONS=("" "" "" "" "󰈤" "" "󰏆" "󰊻" "󰇮")
for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid                             \
            icon=${SPACE_ICONS[$sid -1]}             \
            icon.color=$FG_COLOR                     \
            icon.padding_left=8                      \
            icon.padding_right=8                     \
            icon.align="center"                      \
            background.padding_left=5                \
            background.padding_right=5               \
            background.border_color=$FG_COLOR        \
            background.color=$FG_COLOR               \
            background.border_width=2                \
            background.corner_radius=3               \
            background.height=22                     \
            background.drawing=off                   \
            label.drawing=off                        \
            label="$sid"                             \
            click_script="aerospace workspace $sid"  \
            script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done


##### Adding Left Items #####
# We add some regular items to the left side of the bar
# only the properties deviating from the current defaults need to be set

# sketchybar --add item space_separator left                         \
#            --set space_separator icon=                            \
#                                  background.padding_left=15        \
#                                  background.padding_right=15       \
#                                  label.drawing=off                 \
#                                                                    \
#            --add item front_app  left                              \
#            --set front_app       script="$PLUGIN_DIR/front_app.sh" \
#                                  icon.drawing=off                  \
#            --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

sketchybar --add item clock right                                \
           --set clock update_freq=10                            \
                    script="$PLUGIN_DIR/clock.sh"                \
                    label.color=$BAR_COLOR                       \
                    icon.color=$BAR_COLOR                        \
                    background.color=$FG_COLOR                   \
           --add item utc right                                  \
           --set utc update_freq=10                              \
                    script="$PLUGIN_DIR/utc.sh"                  \
           --add item date right                                 \
           --set date update_freq=3600                           \
                    script="$PLUGIN_DIR/date.sh"                 \
                    label.color=$BAR_COLOR                       \
                    icon.color=$BAR_COLOR                        \
                    background.color=$FG_COLOR                   \
                    icon.padding_right=0                         \
                    icon.padding_left=0                          \
           --add item weekday right                              \
           --set weekday update_freq=3600                        \
                    script="$PLUGIN_DIR/weekday.sh"              \
                    background.padding_left=0                    \
                    background.border_width=1                    \
           --add bracket datetime date utc clock weekday         \
           --set datetime background.color=$FG_COLOR             \
                    background.border_color=$FG_COLOR            \
                    background.border_width=1                    \
                    background.height=26                         \
           --add item battery right                              \
           --set battery script="$PLUGIN_DIR/battery.sh"         \
                    update_freq=10                               \
           --subscribe battery system_woke power_source_change   \
           --add item pomo right                                 \
           --set pomo update_freq=1                              \
                    script="$PLUGIN_DIR/pomo.sh"                 \
                    background.border_color=$FG_COLOR            \
                    background.border_width=1                    \
           --add item github right                               \
           --set github update_freq=120                          \
                    script="$PLUGIN_DIR/github.sh"               \
                    background.border_width=1                    \

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration and
# should never be run in an item script.

sketchybar --update

echo "sketchybar configuration loaded.."
