#!/usr/bin/env bash

function find_sfdx_project_root() {
    sfdx_root=$(pwd -P 2>/dev/null || command pwd)
    while [ ! -e "$sfdx_root/.sfdx" ]; do
        sfdx_root=${sfdx_root%/*}
        if [ "$sfdx_root" = "" ]; then break; fi
    done
    echo $sfdx_root
}

function prompt_sfdx() {
    globalConfig="$(cat ~/.sfdx/sfdx-config.json)";
    sfdx_root=$(find_sfdx_project_root)
    if [ ! $sfdx_root = "" ] && [ ! $sfdx_root = $HOME ]
    then
        localconfig="$(cat $sfdx_root/.sfdx/sfdx-config.json)"    
        defaultusername="u:%B$(echo ${localconfig} | jq -r .defaultusername)%b"
        defaultdevhubusername="d:$(echo ${localconfig} | jq -r .defaultdevhubusername)"
    fi
    if [ -z "$defaultusername" ] || [ "$defaultusername" = "null" ]
    then
        defaultusername="U:%B$(echo ${globalConfig} | jq -r .defaultusername)%b"
    fi
    if [ -z "$defaultdevhubusername" ] || [ "$defaultdevhubusername" = "null" ]
    then
        defaultdevhubusername="D:$(echo ${globalConfig} | jq -r .defaultdevhubusername)"
    fi
    p10k segment -i '' -b white -f blue -t "$defaultdevhubusername $defaultusername"
}

 prompt_sfdx
