#!/usr/bin/env bash

# Dependencies: tesseract-ocr imagemagick pngpaste

SCR_IMG=`mktemp`
trap "rm $SCR_IMG*" EXIT

pngpaste $SCR_IMG.png

mogrify -modulate 100,0 -resize 400% PNG32:$SCR_IMG.png 
#should increase detection rate

tesseract $SCR_IMG.png $SCR_IMG &> /dev/null
cat $SCR_IMG.txt | pbcopy

exit
