#!/bin/zsh

alias sr='sf project reset tracking --no-prompt'
alias ss='sf force:source:status' # ERROR: Unable to convert this command; you must convert it manually.
alias sph='sf force source push --ignorewarnings'
alias spl='sf force source pull --forceoverwrite'
alias sgduat='sf sgd:source:delta --from origin/dev-uat --to HEAD --output .;cat package/package.xml' # ERROR: Unable to convert this command; you must convert it manually.
alias sgdmain='sf sgd:source:delta --from origin/main --to HEAD --output .;cat package/package.xml' # ERROR: Unable to convert this command; you must convert it manually.
alias squash='git merge --squash'
alias log='git log --pretty=oneline --abbrev-commit'

alias backdeploy='git fetch && git rebase origin/main && fsp && git switch dev-stephan && git rebase origin/main && fstr && git switch -'

alias headseton='blueutil --connect 95-05-bb-22-82-e7'
alias headsetoff='blueutil --disconnect 95-05-bb-22-82-e7'

alias gpt='rungpt'
