#!/bin/zsh

alias watch='watch --color ' # hack to enable alias expansion using watch

alias ls='lsd -al' # enhanced ls

# change the kitty theme using a fzf selector
alias switchtheme="find ~/.config/kitty/kitty-themes/themes -iname '*.conf' -printf '%f\n' | sed 's/\.conf$//' | sort -r | fzf | xargs -Ixx kitty @ set-colors --all --configured ~/.config/kitty/kitty-themes/themes/xx.conf"

eval $(thefuck --alias)

case $(hostname) in
  (foxwhelp) source "$ZDOTDIR/aliases-foxwhelp";;
  (sspiegel) source "$ZDOTDIR/aliases-zipari";;
esac

# add more aliases
alias realias="vim ~/dotfiles/zsh/aliases"
