#!/bin/zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export HISTFILE=~/.histfile     # History filepath
export HISTSIZE=10000           # size of history memory
export SAVEHIST=100000          # size of history on disk

# fzf
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Make Java applications work in XMonad
export _JAVA_AWT_WM_NONREPARENTING=1 
