#!/bin/zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# editor
export EDITOR="nvim"
export VISUAL="nvim"

# zsh
export HISTFILE="$ZDOTDIR/.zhistory"     # History filepath
export HISTSIZE=10000           # size of history memory
export SAVEHIST=100000          # size of history on disk

# fzf
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Make Java applications work in XMonad
export _JAVA_AWT_WM_NONREPARENTING=1 

# Android development
export ANDROID_SDK_ROOT=/home/stephan/Android/Sdk/

export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

if [ -e /home/stephan/.nix-profile/etc/profile.d/nix.sh ]; then . /home/stephan/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
