# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Lines configured by zsh-newuser-install

setopt autocd
setopt correct_all # autocorrect commands
setopt extendedglob
setopt hist_ignore_all_dups
setopt hist_reduce_blanks
setopt share_history
setopt nomatch
setopt auto_list # automatically list choices on ambiguous completion
setopt auto_menu # automatically use menu completion
setopt always_to_end # move cursor to end if word had one match
unsetopt beep

bindkey -v # enable vi mode

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/stephan/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
#
_comp_options+=(globdots) # include hidden files in completions
source /usr/share/fzf/completion.zsh    # use fzf completion
source /usr/share/fzf/key-bindings.zsh  # use fzf completion key mappings

source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

source ~/dotfiles/zsh/aliases

# sfdx autocomplete setup
SFDX_AC_ZSH_SETUP_PATH=/home/stephan/.cache/sfdx/autocomplete/zsh_setup \
    && test -f $SFDX_AC_ZSH_SETUP_PATH \
    && source $SFDX_AC_ZSH_SETUP_PATH;

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

### End of Zinit's installer chunk

zinit ice depth=1

# zplug "modules/history-substring-search", from:prezto, defer:2

zinit light zsh-users/zsh-autosuggestions
zinit light zdharma/fast-syntax-highlighting
zinit light djui/alias-tips
zinit light urbainvaes/fzf-marks
zinit light zuxfoucault/colored-man-pages_mod
zinit snippet OMZ::plugins/git/git.plugin.zsh
zinit snippet OMZ::plugins/sudo/sudo.plugin.zsh

zinit light Aloxaf/fzf-tab
zinit light aperezdc/zsh-fzy

bindkey '^R'  fzy-history-widget

# autoload scripts
fpath=( ~/dotfiles/zsh/scripts "${fpath[@]}" )
autoload -Uz $fpath[1]/*(.:t)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
