prSections:
- title: My Pull Requests
  filters: is:open author:@me
  layout:
    author:
      hidden: true
- title: Needs My Review
  filters: is:open review-requested:@me
- title: Involved
  filters: is:open involves:@me -author:@me
- title: Perch Open PRs
  filters: is:open org:BlueWaveFinanceGroup
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
  refetchIntervalMinutes: 30
keybindings:
  prs: []
repoPaths: # configure where to locate repos when checking out PRs
  BlueWaveFinanceGroup/SMP: ~/projects/SMP-worktrees/pr
pager:
  diff: delta
